### PR TITLE
Dev/master/travis

### PR DESCRIPTION
**Pull request by nmorey**
This works on my branch :)
Only thing you should need to do is go to:
https://travis-ci.org/organizations/linux-rdma/repositories
And enable it for ibsim.

I haven't enabled release publishing as it needs a token from someone with access to the repo.
See https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token for a howto.

### CODE REVIEW

**Comment by nmorey** [comment]
Also there were 2 declarations for parsedebug. And no extern. I removed one and added an extern declaration as it seems the right thing to do.
Feel free to have 2 static variables if this was not the case

**Comment by rleon** [comment]
I enabled in travis-ci.

**Comment by rleon** [comment]
Do you want from me to create such OATH token?

**Comment by nmorey** [comment]
That's your call. If you do, you'll get release tarballs automatically generated for you :)

**Comment by nmorey** [comment]
I'll get on OpenSM tomorrow (and probably do infiniband-diags too so we have all the linux-rdma tools in CI)

**Comment by rleon** [comment]
> That's your call. If you do, you'll get release tarballs automatically generated for you :)

It is not really my call, I have no intention to release anything besides rdma-core.

**Comment by rleon** [comment]
> That's your call. If you do, you'll get release tarballs automatically generated for you :)

It is not really my call, I have no intention to release anything besides rdma-core.

**Comment by hnrose** [comment]
Note that infiniBand-diags is moving into rdma-core so I'm not sure you
need to do that.

**Comment by hnrose** [comment]
Manually merged first 3 patches. Only the travis patch remains which I'll test once I hear back on libibverbs-dev.

**Comment by nmorey** [comment]
@rleon I though Hal had sent your message. Thus the misunderstanding :)

@hnrose Submitted without the libibverbs-dev. It is in the SUSE spec file for some reason so I put it in there but you're right, it is not needed.

**Comment by nmorey** [comment]
Should be all good now :)

**Comment by hnrose** [comment]
Manually merged this patch series

**Comment by hnrose** [comment]
Thanks for doing the heavy lifting!

**Comment by nmorey** [comment]
No problem. Here are some more patches to actually run some tests :)

**Comment by hnrose** [comment]
Wow!

Manually merged the additional 12 patches.

**Comment by nmorey** [comment]
@hnrose If you want automated release tarball to be published on github, you'll need to follow the guide here:
 https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token

Or you can ping @rleon. I'm guessing he's familiar with this already :)

**Pull request closed without merging**
